- name: Instalar Apache2 y PHP
  hosts: http
  become: true

  tasks:
    - name: Instalar Apache2
      apt:
        name: apache2
        state: present

    - name: Instalar PHP y módulos
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-xml
        - php-mbstring
        - php-xmlrpc
        - php-zip
        - php-soap
        - php-intl

    - name: Descargar archivo WordPress
      get_url:
        url: "https://drive.google.com/u/0/uc?id=1LYuVL6X9-qZYpXsV2o26-cjpMNRt_NXg&export=download&confirm=t&uuid=55e831fa-37cb-4a57-a457-5d28f05c9203&at=AKKF8vz_7Aq6xfzufZ3WNEX7OsTV:1685707513779"
        dest: /tmp/wordpress.tar
        validate_certs: no

    - name: Copiar archivo WordPress
      copy:
        src: /tmp/wordpress.tar
        dest: /var/www/html/

    - name: Eliminar archivo dir.conf
      file:
        path: /etc/apache2/mods-enabled/dir.conf
        state: absent

    - name: Descargar archivo dir.conf
      get_url:
        url: "https://drive.google.com/u/0/uc?id=1Rz1DBCMdu3RKDcFOkHu0iTQn_JuFgPz2&export=download"
        dest: /tmp/dir.conf
        validate_certs: no

    - name: Copiar archivo dir.conf
      copy:
        src: /tmp/dir.conf
        dest: /etc/apache2/mods-enabled/

    - name: Extraer archivo WordPress
      command: tar xvf /var/www/html/wordpress.tar
      args:
        chdir: /var/www/html/
